export interface ApartmentInterface {
    title: string,
    cost: number,
    square: number,
    rooms: number,
    companyId: string,
    projectId: string | number,
    id: string | number,
    haveBalcony: boolean,
    amount: number,
    isSale: boolean,
    poster: string,
    description: string,
    type: string,
}